"""File store for memory records.

Owns the on-disk layout, frontmatter (de)serialization, safe path handling, and
listing-by-scope. Markdown files are the canonical record; this module is the only place
that reads/writes them. The search adapters only *index/search* what this store writes.
"""

from __future__ import annotations

import re
import secrets
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterator, Optional

import yaml

from app.cruddables.envelope import slugify

from . import config
from .models import MemoryRecord, MemoryScope

# scope_type → top-level directory under the base dir. ``global`` is flat (no scope_id
# subdir); every other scope nests under a slugified scope_id.
SCOPE_DIRS: dict[str, str] = {
    "global": "global",
    "app": "apps",
    "project": "projects",
    "user": "users",
    "session": "sessions",
    "character": "characters",
    "custom": "custom",
    "test": "test",
}

# Memory ids are generated by us and must be filesystem-safe (no separators / traversal).
_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")


class UnsafeMemoryId(ValueError):
    """Raised when a memory id could escape the store (path traversal)."""


def base_dir() -> Path:
    return config.get_config().base_path


def _now_compact() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")


def new_memory_id() -> str:
    return f"mem_{_now_compact()}_{secrets.token_hex(3)}"


def validate_memory_id(memory_id: str) -> str:
    if not memory_id or not _ID_RE.fullmatch(memory_id) or ".." in memory_id:
        raise UnsafeMemoryId(f"unsafe memory id: {memory_id!r}")
    return memory_id


def scope_dir(scope: MemoryScope) -> Path:
    """Resolve the directory for a scope, defending against path traversal in scope_id."""
    top = SCOPE_DIRS.get(scope.scope_type)
    if top is None:
        raise ValueError(f"unknown scope_type: {scope.scope_type!r}")
    base = base_dir()
    if scope.scope_type == "global":
        path = base / top
    else:
        path = base / top / slugify(scope.scope_id or "default")
    resolved = path.resolve()
    base_resolved = base.resolve()
    if base_resolved not in resolved.parents and resolved != base_resolved:
        raise UnsafeMemoryId(f"scope path escapes base dir: {resolved}")
    return path


def record_path(record: MemoryRecord) -> Path:
    validate_memory_id(record.id)
    return scope_dir(record.scope()) / f"{record.id}.md"


# ── frontmatter serialization ────────────────────────────────────────────────


def serialize(record: MemoryRecord) -> str:
    """Render a record to its Markdown-with-frontmatter file text."""
    fm = yaml.safe_dump(
        record.frontmatter(), sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    # body is preserved byte-exact (no trailing-newline coercion)
    return f"---\n{fm}---\n{record.body}"


def parse(text: str) -> MemoryRecord:
    """Parse file text back into a record. Raises ValueError on malformed frontmatter."""
    if not text.startswith("---\n"):
        raise ValueError("missing frontmatter opening fence")
    rest = text[4:]
    marker = rest.find("\n---\n")
    if marker == -1:
        # tolerate a file that is *only* frontmatter ending in '---\n'
        if rest.endswith("---\n"):
            fm_text, body = rest[: -4], ""
        else:
            raise ValueError("missing frontmatter closing fence")
    else:
        fm_text = rest[: marker + 1]
        body = rest[marker + 5 :]
    meta = yaml.safe_load(fm_text) or {}
    if not isinstance(meta, dict):
        raise ValueError("frontmatter is not a mapping")
    known = set(MemoryRecord.model_fields) - {"extra", "body"}
    extra = {k: v for k, v in meta.items() if k not in known}
    fields = {k: v for k, v in meta.items() if k in known}
    return MemoryRecord(**fields, extra=extra, body=body)


# ── read / write ─────────────────────────────────────────────────────────────


def write_record(record: MemoryRecord) -> Path:
    path = record_path(record)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(serialize(record), encoding="utf-8")
    return path


def find_path(memory_id: str) -> Optional[Path]:
    validate_memory_id(memory_id)
    base = base_dir()
    if not base.exists():
        return None
    matches = sorted(base.rglob(f"{memory_id}.md"))
    return matches[0] if matches else None


def read_record(memory_id: str) -> Optional[tuple[MemoryRecord, Path]]:
    path = find_path(memory_id)
    if path is None:
        return None
    return parse(path.read_text(encoding="utf-8")), path


def iter_records(include_deleted: bool = False) -> Iterator[tuple[MemoryRecord, Path]]:
    base = base_dir()
    if not base.exists():
        return
    for path in sorted(base.rglob("*.md")):
        try:
            record = parse(path.read_text(encoding="utf-8"))
        except (ValueError, OSError):
            continue
        if record.status != "active" and not include_deleted:
            continue
        yield record, path


def list_records(
    scopes: Optional[list[MemoryScope]] = None, include_deleted: bool = False
) -> list[tuple[MemoryRecord, Path]]:
    """List records, optionally restricted to one or more scopes.

    An empty/None ``scopes`` lists everything. Scope matching is by
    (scope_type, scope_id) — **except** ``global``, which is one flat namespace
    (see :func:`scope_dir`): requesting any ``global`` scope matches every global
    record regardless of its scope_id, so a global fact is reachable without
    knowing the exact id it was filed under.
    """
    if not scopes:
        return list(iter_records(include_deleted=include_deleted))
    want_global = any(s.scope_type == "global" for s in scopes)
    wanted = {
        (s.scope_type, slugify(s.scope_id or "default"))
        for s in scopes
        if s.scope_type != "global"
    }
    out: list[tuple[MemoryRecord, Path]] = []
    for record, path in iter_records(include_deleted=include_deleted):
        if record.scope_type == "global":
            if want_global:
                out.append((record, path))
        elif (record.scope_type, slugify(record.scope_id or "default")) in wanted:
            out.append((record, path))
    return out


def list_scopes() -> list[dict]:
    """Discover scopes present on disk (for the /scopes debug endpoint)."""
    counts: dict[tuple[str, str], int] = {}
    for record, _ in iter_records(include_deleted=False):
        k = (record.scope_type, record.scope_id)
        counts[k] = counts.get(k, 0) + 1
    return [
        {"scope_type": st, "scope_id": sid, "count": n}
        for (st, sid), n in sorted(counts.items())
    ]


def delete_files_in_scope(scope: MemoryScope) -> int:
    """Hard-delete every ``*.md`` in a scope directory. Used only by the demo reset."""
    d = scope_dir(scope)
    if not d.exists():
        return 0
    removed = 0
    for path in d.glob("*.md"):
        path.unlink()
        removed += 1
    return removed
