"""Unified "cruddable" format — the single source of truth for the app's CRUD entities.

Every in-scope CRUD entity (wildcard, context item, image prompt, chain sequence,
Prompt Pal entry, Hoodat character) is persisted as a :class:`Cruddable` "envelope":
shared meta columns (``id``/``type``/``name``/``description``/``tags``/
``schema_version``/``created_at``/``updated_at``) plus a typed ``data`` payload (the
type-specific "table columns"). The on-disk shape == the export shape == the envelope,
so a collection can be exported, edited (or generated by an external LLM), and
re-imported, and bundled into Packs.

See ``docs/tools/packs.md`` for the format contract.
"""

from __future__ import annotations

from .envelope import Cruddable, slugify, unique_id

__all__ = ["Cruddable", "slugify", "unique_id"]
